name: docs
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-cf-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Build docs
        run: |
          pip install mkdocs-material
          mkdocs build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 1c3512825b9c4527bbbc5c2546a915ec
          command: pages deploy site/ --project-name=prandtl
